//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class productDetailTbl
    {
        public int productDetailID { get; set; }
        public Nullable<int> productID { get; set; }
        public string productDescription { get; set; }
        public Nullable<System.DateTime> productPurchaseDate { get; set; }
        public Nullable<int> productGroupID { get; set; }
        public Nullable<int> supplierID { get; set; }
    
        public virtual productGroupTbl productGroupTbl { get; set; }
        public virtual productTbl productTbl { get; set; }
        public virtual supplierTbl supplierTbl { get; set; }
    }
}
