//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class receiptTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public receiptTbl()
        {
            this.receiptDetailTbl = new HashSet<receiptDetailTbl>();
        }
    
        public int receiptID { get; set; }
        public Nullable<System.DateTime> receiptFormationDate { get; set; }
        public Nullable<double> receiptTotalKDV { get; set; }
        public Nullable<double> receiptTotalPrice { get; set; }
        public string receiptPaymentType { get; set; }
        public Nullable<double> receiptCustomerPay { get; set; }
        public Nullable<double> receiptCashChange { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<receiptDetailTbl> receiptDetailTbl { get; set; }
    }
}
