//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class staffTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public staffTbl()
        {
            this.StaffEntryExitTbl = new HashSet<StaffEntryExitTbl>();
        }
    
        public int staffID { get; set; }
        public string staffTCNumber { get; set; }
        public string staffNameSurname { get; set; }
        public string staffPhoneNo { get; set; }
        public string staffEmail { get; set; }
        public string staffAdress { get; set; }
        public Nullable<int> staffPositionID { get; set; }
        public Nullable<int> staffSalary { get; set; }
        public string staffPassword { get; set; }
        public Nullable<System.DateTime> staffStartDate { get; set; }
        public Nullable<System.DateTime> staffFinishDate { get; set; }
        public Nullable<bool> staffIsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StaffEntryExitTbl> StaffEntryExitTbl { get; set; }
        public virtual staffPositionTbl staffPositionTbl { get; set; }
    }
}
