//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffEntryExitTbl
    {
        public int staffEntryExitID { get; set; }
        public Nullable<int> staffID { get; set; }
        public Nullable<System.DateTime> entryDateTime { get; set; }
        public Nullable<System.DateTime> exitDateTime { get; set; }
        public Nullable<bool> leaveStatus { get; set; }
    
        public virtual staffTbl staffTbl { get; set; }
    }
}
