//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_Management
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplierTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplierTbl()
        {
            this.productDetailTbl = new HashSet<productDetailTbl>();
        }
    
        public int supplierID { get; set; }
        public string supplierName { get; set; }
        public string supplierPhoneNumber { get; set; }
        public string supplierIBAN { get; set; }
        public string supplierEmail { get; set; }
        public string supplierAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<productDetailTbl> productDetailTbl { get; set; }
    }
}
